### ISSUE TITLE
Failure & coredump `check-environment.sh` using `blosc` filter

### ISSUE THREAD

**Issue by truth-quark** [OpenDataCubePipelines/ard-pipeline#59]
On my local system, after installing `conda` & building the environment as per the README. Running `deployment/check-environment.sh` failed here:

https://github.com/OpenDataCubePipelines/ard-pipeline/blob/ea84164ab0cd4fb13188984bfd4332d7eb6b59e1/deployment/check-environment.sh#L55

The output:

```Bash
# ... other tests passing

Attempting hdf5 blosc compression...python3: /home/conda/feedstock_root/build_artifacts/libnetcdf_1702228817425/work/plugins/H5Zblosc.c:160: blosc_set_local: Assertion `nelements == 7' failed.
./ard-pipeline/deployment/check-environment.sh: line 63: 121505 Aborted                 (core dumped) python3 <<EOF

# rest of embedded python code printed to terminal
```

Modifying `check-environment.sh`'s embedded python to use `hdf5plugin` directly solves the core dump:

```Python
# The previous import of wagl should have initialised the filters.
print("Attempting hdf5 blosc compression...", end='', flush=True)
import h5py
import hdf5plugin  # for filter plugins
import tempfile
f = h5py.File(tempfile.mktemp('-test.h5'),'w')

# FIX: change compression from int to a plugin
dset = f.create_dataset("myData", (100, 100), compression=hdf5plugin.Blosc())
```

**Comment by truth-quark** [comment]
@uchchwhash @jeremyh are you aware of any reasons against using `hdf5plugin`s for the compression arg?

**Comment by jeremyh** [comment]
hdf5plugin is what we use already — the comment higher up mentions it indirectly: `# The previous import of wagl should have initialised the filters.`

In wagl we import it here: https://github.com/OpenDataCubePipelines/ard-pipeline/blob/e841eb271a1bf5050394ca6365abb4302ecb8cc8/wagl/__init__.py#L3

So somehow it is no longer being included implictly by the wagl import?

**Comment by jeremyh** [comment]
Ah, I see — it's the number that's the problem, not the import itself. Perhaps something has changed in a library upgrade and that hardcoded number is not a sensible choice?

**Comment by truth-quark** [comment]
> So somehow it is no longer being included implictly by the wagl import?

I'm not sure of the specifics - it's buried somewhere & I haven't delved into it.

> Ah, I see — it's the number that's the problem, not the import itself. 

Removing the `int` code & `compression` arg allowed the test to pass. Also, using `hdf5plugin` for the compression arg brought in more error handling. Deliberately _breaking_ the code with `compression=hdf5plugin` & `compression=hdf5plugin.Blosc` (no func call) was raised exceptions, so better than a core dump (some failures crashed the conda env).

**Comment by truth-quark** [comment]
> .... but if a raw number doesn't work, does wagl itself work? I can see the blosc int used here:
> 
> https://github.com/OpenDataCubePipelines/ard-pipeline/blob/b53ca81476f3cf4e96769a462fce95b3d5bd5383/wagl/hdf5/compression.py#L258

I haven't run `wagl` yet to find out definitively.

In the meantime, I'll experiment with changing `compression=<plugin>` across the codebase to run that through the GitHub actions.

**Comment by truth-quark** [comment]
> > .... but if a raw number doesn't work, does wagl itself work? I can see the blosc int used here:
> > https://github.com/OpenDataCubePipelines/ard-pipeline/blob/b53ca81476f3cf4e96769a462fce95b3d5bd5383/wagl/hdf5/compression.py#L258
> 
>... I'll experiment with changing `compression=<plugin>` across the codebase ...

With some `grep` work, I can't find any evidence in the code that the `blosc` filter is being used. Compression mostly defaults to `LZF` filters.

Is `blosc` compression used in any production runs?

If not, is there any issue with modifying `check-environment` script to use the default `LZF`?

**Comment by uchchwhash** [comment]
> Is `blosc` compression used in any production runs?

No.

> If not, is there any issue with modifying `check-environment` script to use the default `LZF`?

No.

**Comment by truth-quark** [comment]
> > Is `blosc` compression used in any production runs?
> 
> No.
> 
> > If not, is there any issue with modifying `check-environment` script to use the default `LZF`?
> 
> No.

Ok, I'll create a change on a new branch & ask @sixy6e to try the `check-environment` script for a sanity check.

**Comment by sixy6e** [comment]
The issue is actually to do with the fact that the `compression_opts` argument is empty, and for blosc it's expecting a tuple/list containing 7 elements; hence your error on the `assertion nelements == 7`.

Here's a snippet of how you should be setting it up:

```python
from wagl import hdf5
comp = hdf5.compression.H5CompressionFilter.BLOSC_ZSTANDARD
config = comp.config(chunks=(200, 300), aggression=9)
kwargs = config.dataset_compression_kwargs()
# print(kwargs)  to actually see what it comes back as
# {'chunks': (200, 300), 'shuffle': False, 'compression': 32001, 'compression_opts': (0, 0, 0, 0, 9, 1, 5)}
```

The `hdf5plugin.Blosc()` is a similar wrapper to what we have, and sets up the required params eg:

```python
>>> dict(hdf5plugin.Blosc())
{'compression': 32001, 'compression_opts': (0, 0, 0, 0, 5, 1, 1)}
```
